import { isSupabaseConfigured } from "./lib/supabase.js";
import { ensureGuestSession } from "./services/auth.js";
import { uploadAvatar } from "./services/storage.js";
import { playBirthday, playChatBubble, playDiceResult, playDiceRoll, playGiftReveal, playGiftTick, playNegativeMove, playTurboMove, playVictory, toggleAudio } from "./services/audio.js";
import {
  addPlayer as addRemotePlayer,
  createRoom as createRemoteRoom,
  deleteRoom as deleteRemoteRoom,
  expirePendingItem as expireRemoteItem,
  enterRoom as enterRemoteRoom,
  heartbeatRoom as heartbeatRemoteRoom,
  getBirthdayEvent,
  findRoom as findRemoteRoom,
  listRooms as listRemoteRooms,
  listActiveChat,
  leaveRoom as leaveRemoteRoom,
  removePlayer as removeRemotePlayer,
  rollD20 as rollRemoteD20,
  startRace as startRemoteRace,
  subscribeToRoom,
  sendChatMessage,
  useItem as useRemoteItem
} from "./services/rooms.js";

const $ = (selector) => document.querySelector(selector);
const STORAGE_KEY = "d20-racing-rooms-v2";
const colors = ["#ff5a1f", "#38bdf8", "#a78bfa", "#39e58c", "#fbbf24", "#fb7185"];
const state = { rooms: loadRooms(), room: null, pilots: [], laps: 3, turn: 0, racing: false, photo: "", joinMode: "racer", guestId: getGuestId(), cloud: false, unsubscribe: null, refreshTimer: null, refreshPromise: null, refreshQueued: false, presenceTimer: null, watchingOnly: false, pendingExpiryTimer: null, pendingCountdown: null, lastEventId: "none", giftEventTimer: null, winnerAnnouncedId: null, finalModalScheduled: null, chatBubbles: {}, chatTimers: {}, chatMessages: [], chatSeenIds: new Set(), turnPermissionTimer: null, turnAnnouncementTimer: null, lastAnnouncedTurnId: null, diceResultTimer: null, lastDisplayedRollId: null, pendingLocalDiceValue: null, nextScreenAnimationAt: 0, visualGeneration: 0, sequenceLocked: false, giftFlowActive: false, queuedPendingGiftId: null, birthdayEvent: null, adminSelectedPilotId: null, deferredScores: {}, postRaceLobby: false };
const chatEmotes = {none:"",wave:"👋",laugh:"😂",fire:"🔥",wow:"😮",gg:"🏁",sad:"😢",angry:"😡"};

$("#soundToggle").onclick=event=>{const muted=toggleAudio();event.currentTarget.textContent=muted?"🔇":"🔊";event.currentTarget.classList.toggle("is-muted",muted);event.currentTarget.setAttribute("aria-label",muted?"Ativar efeitos sonoros":"Desativar efeitos sonoros");};

function loadRooms() { try { const rooms=JSON.parse(localStorage.getItem(STORAGE_KEY))||[],cutoff=Date.now()-86400000,fresh=rooms.filter(room=>{const created=new Date(room.createdAt).getTime();return !Number.isFinite(created)||created>=cutoff;});if(fresh.length!==rooms.length)localStorage.setItem(STORAGE_KEY,JSON.stringify(fresh));return fresh; } catch { return []; } }
function getGuestId() { let id=localStorage.getItem("d20-racing-guest-id"); if(!id){id=crypto.randomUUID?.()||`guest-${Date.now()}-${Math.random()}`;localStorage.setItem("d20-racing-guest-id",id);} return id; }
function spectatorKey(code){return `d20-racing-spectator-${code}`;}
function setWatchingOnly(value){state.watchingOnly=Boolean(value);if(!state.room)return;if(value)localStorage.setItem(spectatorKey(state.room.code),"1");else localStorage.removeItem(spectatorKey(state.room.code));}
function startPresenceHeartbeat(){if(state.presenceTimer)clearInterval(state.presenceTimer);if(!state.cloud||!state.room)return;state.presenceTimer=setInterval(()=>heartbeatRemoteRoom(state.room?.code).catch(()=>{}),30000);}
function isHost() { return state.room?.ownerId===state.guestId; }
function ownsPilot(pilot) { return pilot?.ownerId===state.guestId; }
function canRollCurrentPilot() { const pilot=state.pilots[state.turn];return ownsPilot(pilot)||(isHost()&&Date.now()>=new Date(state.room?.turnStartedAt||0).getTime()+60000); }
function saveRooms() { if(state.cloud)return;try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.rooms)); } catch { toast("O navegador ficou sem espaço para salvar mais fotos."); } }
function escapeHTML(value) { return String(value).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c])); }
function toast(message) { const el=$("#toast"); el.textContent=message; el.classList.add("show"); setTimeout(()=>el.classList.remove("show"),2200); }
function showOnly(...ids) { document.querySelectorAll(".page").forEach(el=>el.hidden=!ids.includes(el.id)); }
function generateCode() { const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; let code=""; do { code=Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join(""); } while(state.rooms.some(r=>r.code===code)); return code; }
function renderChatControls(){const owned=state.pilots.filter(ownsPilot),form=$("#chatForm"),select=$("#chatPilot"),signature=owned.map(p=>`${p.id}:${p.name}`).join("|");form.hidden=owned.length===0;$("#chatUnavailable").hidden=owned.length>0;if(select.dataset.signature===signature)return;const selected=select.value;select.dataset.signature=signature;select.innerHTML=owned.map(p=>`<option value="${p.id}">${escapeHTML(p.name)}</option>`).join("");if(owned.some(p=>p.id===selected))select.value=selected;}
function showChatBubble(message){if(!message?.player_id||!state.pilots.some(p=>p.id===message.player_id)||state.chatSeenIds.has(message.id))return;const remaining=new Date(message.expires_at).getTime()-Date.now();if(remaining<=0)return;if(message.id)state.chatSeenIds.add(message.id);state.chatMessages.push(message);state.chatMessages=state.chatMessages.slice(-20);state.chatBubbles[message.player_id]={message:message.message,emote:message.emote,isNew:true};clearTimeout(state.chatTimers[message.player_id]);state.chatTimers[message.player_id]=setTimeout(()=>{delete state.chatBubbles[message.player_id];delete state.chatTimers[message.player_id];if(state.room)renderRace();},remaining);playChatBubble();renderChatFeed();if(state.racing||state.room?.status==="finished")renderRace();}
function renderChatFeed(){const feed=$("#chatFeed");if(!feed)return;const visible=state.chatMessages.map(message=>({message,pilot:state.pilots.find(p=>p.id===message.player_id)})).filter(item=>item.pilot),signature=visible.map(({message,pilot})=>`${message.id}:${pilot.id}`).join("|");if(feed.dataset.signature===signature)return;feed.dataset.signature=signature;feed.innerHTML=visible.map(({message,pilot})=>`<article class="chat-line"><img src="${pilot.photo}" alt=""><div><strong>${escapeHTML(pilot.name)}</strong><p>${chatEmotes[message.emote]?`<b>${chatEmotes[message.emote]}</b>`:""}${escapeHTML(message.message)}</p></div></article>`).join("");feed.scrollTop=feed.scrollHeight;$("#chatEmpty").hidden=visible.length>0;}

function makeAvatar(seed="D20") { const initials=seed.slice(0,2).toUpperCase(),color=colors[Math.floor(Math.random()*colors.length)]; const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160"><rect width="160" height="160" fill="${color}"/><circle cx="80" cy="62" r="31" fill="#f6d2b8"/><path d="M22 160c4-44 26-65 58-65s54 21 58 65" fill="#07111f"/><path d="M48 55c2-28 18-40 35-40 20 0 35 16 35 43-13-7-23-18-29-28-8 12-24 22-41 25z" fill="#15263a"/><text x="80" y="145" text-anchor="middle" font-family="Arial" font-weight="bold" font-size="18" fill="white">${initials}</text></svg>`; return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`; }
function setPhoto(src) { state.photo=src; const p=$("#photoPreview"); p.textContent=""; p.style.backgroundImage=`url("${src}")`; }

function normalizePlayer(player){return {id:player.id,ownerId:player.owner_id,name:player.codename,photo:player.avatar_url||makeAvatar(player.codename),score:player.score||0,rolls:player.roll_count||0,finishPosition:player.finish_position,finishedAt:player.finished_at,isSpectator:Boolean(player.is_spectator),spectatorOnly:Boolean(player.spectator_only)};}
function normalizeRoom(room){return {id:room.id,code:room.code,name:room.name,laps:room.laps,maxPlayersPerUser:room.max_players_per_user||1,ownerId:room.owner_id,status:room.status,currentPlayerId:room.current_player_id,turnStartedAt:room.turn_started_at||room.updated_at,pendingItem:room.pending_item,lastEvent:room.last_event,lastRoll:room.last_roll,claimedGifts:room.claimed_gifts||[],birthdayCakeClaims:room.birthday_cake_claims||[],winnerId:room.winner_id,pilots:(room.players||[]).map(normalizePlayer),createdAt:room.created_at};}
function isBirthdayActive(){const event=state.birthdayEvent,now=Date.now();return Boolean(event&&now>=new Date(event.starts_at).getTime()&&now<new Date(event.ends_at).getTime());}
function scheduleBirthdayExpiry(){const delay=new Date(state.birthdayEvent?.ends_at).getTime()-Date.now();if(delay>0&&delay<2147483647)setTimeout(()=>{state.birthdayEvent=null;if(state.room)renderRace();},delay+100);}
async function reloadRemoteRooms(){state.rooms=(await listRemoteRooms()).map(normalizeRoom);renderDashboard();}
function prepareDeferredGiftMovement(room,previousPilots){const event=room.lastEvent;if(!event||event.id===state.lastEventId)return;const pilotId=event.type==="turbo"||event.type==="finish"||event.type==="birthday_cake"?event.source_id:event.target_id,previous=previousPilots.find(p=>p.id===pilotId);if(previous)state.deferredScores[pilotId]=previous.score;}
async function refreshCurrentRoom(){
  if(state.refreshTimer){clearTimeout(state.refreshTimer);state.refreshTimer=null;}
  if(!state.cloud||!state.room)return;
  const remote=await findRemoteRoom(state.room.code);if(!remote){goDashboard();toast("A sala foi encerrada.");return;}
  const previousPilots=state.pilots,room=normalizeRoom(remote),newRoll=room.lastRoll?.id&&room.lastRoll.id!==state.lastDisplayedRollId;prepareDeferredGiftMovement(room,previousPilots);if(newRoll){const previous=previousPilots.find(p=>p.id===room.lastRoll.player_id);if(previous)state.deferredScores[room.lastRoll.player_id]=previous.score;}state.room=room;state.pilots=room.pilots;state.rooms=state.rooms.map(r=>r.code===room.code?room:r);state.turn=Math.max(0,state.pilots.findIndex(p=>p.id===room.currentPlayerId));if(room.lastRoll){$("#lastRoll").textContent=room.lastRoll.value;if(newRoll){state.lastDisplayedRollId=room.lastRoll.id;if(Number(room.lastRoll.value)===state.pendingLocalDiceValue)state.pendingLocalDiceValue=null;else showDiceResult(room.lastRoll.value);const rolled=state.pilots.find(p=>p.id===room.lastRoll.player_id),intermediate=room.lastEvent?.type==="birthday_cake"&&room.lastEvent.effect==="spiked"?rolled?.score+3:null;queueTrackMovement(room.lastRoll.player_id,intermediate);}}processPublicGiftEvent(room);
  if(room.status==="racing"){state.racing=true;$("#raceActions").hidden=false;$("#hostBackToLobby").hidden=!isHost();$("#activeRaceName").textContent=room.name;$("#raceCode").textContent=`SALA ${room.code}`;$("#raceLapSummary").textContent=`${room.laps} ${room.laps===1?"VOLTA":"VOLTAS"}`;if(isHost()&&state.postRaceLobby){showOnly("lobby","gridSection");renderGrid();return;}if(!isHost()&&!state.pilots.some(ownsPilot)&&!state.watchingOnly){showOnly("lobby","gridSection");renderGrid();toast("Crie um corredor para a próxima largada ou entre apenas como espectador.");return;}showOnly("raceSection");renderRace();updateRollPermission();if(room.pendingItem){schedulePendingExpiry(room.pendingItem);const source=state.pilots.find(p=>p.id===room.pendingItem.player_id);if(ownsPilot(source))showRemoteItem(room.pendingItem);else hideRemoteItem(true);}else hideRemoteItem();}
  else if(room.status==="finished"&&room.winnerId){hideRemoteItem();state.racing=false;if(state.postRaceLobby){showOnly("lobby","gridSection");renderGrid();}else{$("#raceActions").hidden=true;showOnly("raceSection");renderRace();$("#currentPilot").textContent="FIM DA CORRIDA";$("#turnPermission").textContent="Confira a classificação final ao lado.";$("#rollButton").disabled=true;}}
  else{hideRemoteItem();showOnly("lobby","gridSection");renderGrid();}
}
function scheduleRoomRefresh(){if(state.refreshTimer)clearTimeout(state.refreshTimer);state.refreshTimer=setTimeout(()=>{state.refreshTimer=null;if(state.refreshPromise){state.refreshQueued=true;return;}state.refreshPromise=refreshCurrentRoom().catch(error=>toast(error.message)).finally(()=>{state.refreshPromise=null;if(state.refreshQueued){state.refreshQueued=false;scheduleRoomRefresh();}});},90);}

function renderDashboard() {
  $("#headerStatus").textContent="Dashboard"; $("#roomCount").textContent=state.rooms.length; $("#roomsEmpty").hidden=state.rooms.length>0;
  $("#roomsGrid").innerHTML=state.rooms.map(room=>`<article class="room-card"><small>SALA ${room.code}</small><h3>${escapeHTML(room.name)}</h3><div class="room-card-meta"><span>${room.laps} VOLTAS</span><span>${room.pilots?.length||0} PILOTOS</span></div><button data-code="${room.code}">ABRIR SALA →</button></article>`).join("");
}
async function goDashboard(){if(state.unsubscribe){state.unsubscribe();state.unsubscribe=null;}if(state.refreshTimer){clearTimeout(state.refreshTimer);state.refreshTimer=null;}state.refreshQueued=false;if(state.presenceTimer){clearInterval(state.presenceTimer);state.presenceTimer=null;}hideRemoteItem();state.room=null;state.pilots=[];state.racing=false;state.watchingOnly=false;history.replaceState(null,"",location.pathname);showOnly("dashboard");if(state.cloud)await reloadRemoteRooms();else renderDashboard();scrollTo({top:0});}
async function removeCurrentRoom(){if(!state.room)return;if(state.cloud)await deleteRemoteRoom(state.room.code);else{state.rooms=state.rooms.filter(room=>room.code!==state.room.code);saveRooms();}await goDashboard();}
async function leaveCurrentRoom(){if(!state.room)return;const hostLeaving=isHost(),ownPilots=state.pilots.filter(ownsPilot),roomName=state.room.name;localStorage.removeItem(spectatorKey(state.room.code));if(state.cloud){await leaveRemoteRoom(state.room.code);await goDashboard();}else{if(ownPilots.length){const ids=new Set(ownPilots.map(p=>p.id));state.pilots=state.pilots.filter(p=>!ids.has(p.id));syncRoom();}if(state.pilots.length===0&&(ownPilots.length||hostLeaving))await removeCurrentRoom();else await goDashboard();}toast(ownPilots.length?`Você saiu de ${roomName}. Seus corredores foram removidos.`:`Você saiu de ${roomName}.`);}
function openRoom(room) {
  if(state.room?.code!==room.code){state.chatMessages=[];state.chatBubbles={};state.chatSeenIds.clear();state.adminSelectedPilotId=null;state.lastAnnouncedTurnId=null;state.lastDisplayedRollId=room.lastRoll?.id||null;state.nextScreenAnimationAt=0;state.sequenceLocked=false;state.queuedPendingGiftId=null;state.visualGeneration++;}
  if(!room.ownerId&&!state.cloud){room.ownerId=state.guestId;saveRooms();}
  room.maxPlayersPerUser=room.maxPlayersPerUser||1;state.room=room; state.pilots=room.pilots||[]; state.laps=room.laps; state.racing=false;state.watchingOnly=localStorage.getItem(spectatorKey(room.code))==="1";state.postRaceLobby=room.status==="finished";state.lastEventId=room.lastEvent?.id||"none";
  $("#roomCodeLabel").textContent=room.code; $("#roomRaceName").textContent=room.name; $("#roomLaps").textContent=`${room.laps} ${room.laps===1?"volta":"voltas"}`; $("#headerStatus").textContent=`Sala ${room.code}`;
  $("#deleteRoom").hidden=!isHost(); history.replaceState(null,"",`${location.pathname}?sala=${room.code}`); showOnly("lobby","gridSection"); renderGrid(); scrollTo({top:0});if(state.cloud&&room.id){enterRemoteRoom(room.code,state.watchingOnly).then(startPresenceHeartbeat).catch(()=>{});if(state.unsubscribe)state.unsubscribe();state.unsubscribe=subscribeToRoom(room.id,payload=>{if(payload.table==="chat_messages")showChatBubble(payload.new);else scheduleRoomRefresh();});refreshCurrentRoom().then(()=>listActiveChat(room.id)).then(messages=>messages.forEach(showChatBubble)).catch(error=>toast(error.message));}
}
function syncRoom() { if(!state.room||state.cloud)return; state.room.pilots=state.pilots; const i=state.rooms.findIndex(r=>r.code===state.room.code); if(i>=0)state.rooms[i]=state.room; saveRooms(); }

$("#showCreateRoom").onclick=()=>{showOnly("createRoomPage"); $("#headerStatus").textContent="Nova sala";};
$("#homeButton").onclick=goDashboard;
$("#leaveRoom").onclick=()=>{if(confirm("Sair da sala? Seu corredor será removido do grid."))leaveCurrentRoom();};
$("#leaveRace").onclick=()=>{if(confirm("Sair da corrida? Seu corredor será removido do grid."))leaveCurrentRoom();};
$("#hostBackToLobby").onclick=()=>{if(!isHost())return;state.postRaceLobby=true;showOnly("lobby","gridSection");renderGrid();scrollTo({top:0});};
$("#deleteRoom").onclick=async()=>{if(!isHost())return toast("Somente o criador pode excluir a sala.");if(confirm("Excluir esta sala e todos os corredores? Esta ação não pode ser desfeita.")){try{await removeCurrentRoom();toast("Sala excluída.");}catch(error){toast(error.message);}}};
document.querySelectorAll(".lap-picker button").forEach(btn=>btn.onclick=()=>{state.laps=Math.max(1,Math.min(12,state.laps+Number(btn.dataset.step))); $("#lapDisplay").textContent=state.laps;});
document.querySelectorAll(".lap-quick button").forEach(btn=>btn.onclick=()=>{state.laps=Number(btn.dataset.laps);$("#lapDisplay").textContent=state.laps;document.querySelectorAll(".lap-quick button").forEach(b=>b.classList.toggle("selected",b===btn));});
$("#createRoomForm").onsubmit=async e=>{e.preventDefault();try{const maxPlayersPerUser=Number($("#maxPlayersPerUser").value);let room;if(state.cloud)room=normalizeRoom(await createRemoteRoom({name:$("#raceName").value.trim(),laps:state.laps,maxPlayersPerUser}));else{room={code:generateCode(),name:$("#raceName").value.trim(),laps:state.laps,maxPlayersPerUser,pilots:[],ownerId:state.guestId,createdAt:Date.now()};state.rooms.unshift(room);saveRooms();}e.target.reset();openRoom(room);toast(`Sala ${room.code} criada!`);}catch(error){toast(error.message);}};
$("#roomCodeInput").oninput=e=>{if(e.inputType==="insertFromPaste")return;const code=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);e.target.value=code;};
$("#roomCodeInput").onpaste=e=>{e.preventDefault();const pasted=e.clipboardData.getData("text").trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(pasted))return toast("Cole somente o código de 6 caracteres da sala.");e.currentTarget.value=pasted;};
$("#joinRoomForm").onsubmit=async e=>{e.preventDefault();const code=$("#roomCodeInput").value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);if(code.length!==6)return toast("Digite os 6 caracteres do código.");try{const remote=state.cloud?await findRemoteRoom(code):null,room=state.cloud?(remote?normalizeRoom(remote):null):state.rooms.find(r=>r.code===code);if(!room)return toast(`A sala ${code} não foi encontrada.`);$("#roomCodeInput").value="";openRoom(room);}catch(error){toast(`Não foi possível entrar: ${error.message}`);}};
$("#roomsGrid").onclick=e=>{const btn=e.target.closest("[data-code]"); if(btn)openRoom(state.rooms.find(r=>r.code===btn.dataset.code));};
$("#copyCode").onclick=async()=>{try{await navigator.clipboard.writeText(state.room.code);toast(`Código ${state.room.code} copiado!`);}catch{toast(`Código: ${state.room.code}`);}};
$("#copyRoomLink").onclick=async()=>{const url=`${location.origin}${location.pathname}?sala=${state.room.code}`;try{await navigator.clipboard.writeText(url);toast("Link da sala copiado!");}catch{toast(url);}};

function handleImage(file) { if(!file?.type.startsWith("image/"))return toast("Solte um arquivo de imagem."); if(file.size>4*1024*1024)return toast("Escolha uma imagem de até 4 MB."); const reader=new FileReader(); reader.onload=()=>{const img=new Image();img.onload=()=>{const size=320,canvas=document.createElement("canvas"),ctx=canvas.getContext("2d"),side=Math.min(img.width,img.height),sx=(img.width-side)/2,sy=(img.height-side)/2;canvas.width=size;canvas.height=size;ctx.drawImage(img,sx,sy,side,side,0,0,size,size);setPhoto(canvas.toDataURL("image/jpeg",.82));};img.src=reader.result;}; reader.readAsDataURL(file); }
$("#photoInput").onchange=e=>handleImage(e.target.files[0]);
const drop=$("#photoDropzone"); ["dragenter","dragover"].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.add("dragging");})); ["dragleave","drop"].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.remove("dragging");})); drop.addEventListener("drop",e=>handleImage(e.dataTransfer.files[0]));
$("#randomAvatar").onclick=()=>setPhoto(makeAvatar($("#codename").value||"D20")); $("#codename").oninput=e=>$("#charCount").textContent=`${e.target.value.length}/16`;

document.querySelectorAll("[data-join-mode]").forEach(button=>button.onclick=()=>{state.joinMode=button.dataset.joinMode;document.querySelectorAll("[data-join-mode]").forEach(item=>item.classList.toggle("selected",item===button));$("#joinSubmitButton").innerHTML=state.joinMode==="spectator"?'ENTRAR COMO ESPECTADOR <span>→</span>':'ADICIONAR AO GRID <span>→</span>';});
$("#joinForm").onsubmit=async e=>{e.preventDefault();if(state.pilots.filter(ownsPilot).length>=state.room.maxPlayersPerUser)return toast("Você atingiu o limite de perfis desta sala.");const name=$("#codename").value.trim(),spectatorOnly=state.joinMode==="spectator";if(state.pilots.some(p=>p.name.toLowerCase()===name.toLowerCase()))return toast("Esse codinome já está em uso.");try{setWatchingOnly(spectatorOnly);if(state.cloud){await enterRemoteRoom(state.room.code,spectatorOnly);const id=crypto.randomUUID(),photo=await uploadAvatar({userId:state.guestId,playerId:id,dataUrl:state.photo||makeAvatar(name)});await addRemotePlayer({id,roomId:state.room.id,codename:name,avatarUrl:photo,spectatorOnly});await refreshCurrentRoom();}else{state.pilots.push({id:crypto.randomUUID?.()||String(Date.now()),ownerId:state.guestId,name,photo:state.photo||makeAvatar(name),score:0,rolls:0,isSpectator:spectatorOnly||state.room.status==="racing",spectatorOnly});syncRoom();}e.target.reset();state.photo="";$("#photoPreview").style.backgroundImage="";$("#photoPreview").textContent="+";$("#charCount").textContent="0/16";renderGrid();if(spectatorOnly&&state.room.status==="racing"){showOnly("raceSection");renderRace();updateRollPermission();}toast(spectatorOnly?`${name} entrou como espectador e já pode usar o chat.`:state.room.status==="racing"?`${name} aguardará a próxima largada.`:`${name} entrou na corrida!`);}catch(error){toast(error.message);}};
function renderGrid(){const owned=state.pilots.filter(ownsPilot).length,activeRacers=state.pilots.filter(p=>!p.spectatorOnly),limit=state.room.maxPlayersPerUser||1,limitReached=owned>=limit;$("#joinForm").hidden=limitReached;$("#joinModePicker").hidden=limitReached;$("#joinedMessage").hidden=owned===0;$("#joinedMessage strong").textContent=`✓ SEUS PERFIS: ${owned}/${limit}`;$("#roleBadge").textContent=isHost()?"DONO DA SALA":state.pilots.some(p=>ownsPilot(p)&&p.spectatorOnly)?"ESPECTADOR":"VISITANTE";$("#roleBadge").classList.toggle("role-badge--host",isHost());$("#pilotCount").textContent=activeRacers.length;$("#emptyState").hidden=state.pilots.length>0;$("#pilotGrid").innerHTML=state.pilots.map((p,i)=>`<article class="pilot-card ${ownsPilot(p)?"pilot-card--mine":""}">${(isHost()||ownsPilot(p))?`<button class="remove-pilot" data-id="${p.id}" aria-label="Remover ${escapeHTML(p.name)}">×</button>`:""}<img src="${p.photo}" alt="Foto de ${escapeHTML(p.name)}"><h3>${escapeHTML(p.name)}</h3><small>${p.spectatorOnly?"ESPECTADOR":p.isSpectator?"AGUARDANDO PRÓXIMA CORRIDA":`PILOTO ${String(i+1).padStart(2,"0")}`}</small>${ownsPilot(p)?'<small class="pilot-owner">SEU PERFIL</small>':""}</article>`).join("");const b=$("#startRace");if(state.room.status==="racing"&&isHost()){b.disabled=false;b.textContent="VOLTAR À CORRIDA →";}else{b.disabled=activeRacers.length<2||!isHost();b.textContent=!isHost()?"AGUARDANDO O DONO DA SALA":activeRacers.length<2?"PRECISA DE 2 CORREDORES":`INICIAR ${state.room.laps} ${state.room.laps===1?"VOLTA":"VOLTAS"} →`;}}
$("#pilotGrid").onclick=async e=>{const b=e.target.closest(".remove-pilot");if(!b)return;const pilot=state.pilots.find(p=>p.id===b.dataset.id);if(!isHost()&&!ownsPilot(pilot))return toast("Você não pode remover este corredor.");try{if(state.cloud){await removeRemotePlayer(pilot.id);await refreshCurrentRoom();}else{state.pilots=state.pilots.filter(p=>p.id!==b.dataset.id);syncRoom();renderGrid();}}catch(error){toast(error.message);}};

async function startRace(){if(!isHost())return toast("Somente o dono da sala pode iniciar a corrida.");if(state.room.status==="racing"&&state.postRaceLobby){state.postRaceLobby=false;showOnly("raceSection");renderRace();updateRollPermission();scrollTo({top:0});return;}try{state.postRaceLobby=false;state.lastAnnouncedTurnId=null;state.giftFlowActive=false;if(state.cloud){await startRemoteRace(state.room.code);await refreshCurrentRoom();}else{state.pilots.forEach(p=>{p.score=0;p.rolls=0;p.claimedGifts=[];});state.turn=0;}state.racing=true;state.pendingGift=null;state.winnerAnnouncedId=null;$("#raceActions").hidden=false;$("#activeRaceName").textContent=state.room.name;$("#raceCode").textContent=`SALA ${state.room.code}`;$("#raceLapSummary").textContent=`${state.room.laps} ${state.room.laps===1?"VOLTA":"VOLTAS"}`;$("#lastRoll").textContent="—";$("#mysteryModal").hidden=true;showOnly("raceSection");renderRace();updateRollPermission();scrollTo({top:0});}catch(error){toast(error.message);}}
function renderRace(){
  const total=state.room.laps*100,track=$("#raceTrack"),racingPilots=state.pilots.filter(p=>!p.isSpectator),pilotIds=new Set(racingPilots.map(p=>p.id));
  track.dataset.raceName=state.room.name;
  if(track.dataset.room!==state.room.code){track.innerHTML=`<div class="track-marker marker-25" data-marker="25">🎁<small>MARCO 25</small></div><div class="track-marker marker-50" data-marker="50">🎁<small>MARCO 50</small></div><div class="track-marker marker-75" data-marker="75">🎁<small>MARCO 75</small></div>`;track.dataset.room=state.room.code;}
  const currentPilot=state.pilots[state.turn],ownedPerspective=state.pilots.find(p=>ownsPilot(p)&&!p.spectatorOnly),giftPerspective=ownsPilot(currentPilot)?currentPilot:ownedPerspective||currentPilot,currentLap=giftPerspective?Math.min(state.room.laps,Math.floor(giftPerspective.score/100)+1):1,claimed=new Set((state.room.claimedGifts||[]).filter(g=>g.player_id===giftPerspective?.id&&g.lap===currentLap).map(g=>Number(g.marker)));track.querySelectorAll(".track-marker").forEach(marker=>marker.classList.toggle("is-consumed",claimed.has(Number(marker.dataset.marker))));renderBirthdayCakes(track,giftPerspective);
  track.querySelectorAll(".oval-racer").forEach(element=>{if(!pilotIds.has(element.dataset.pilot))element.remove();});
  racingPilots.forEach((pilot,index)=>{
    let racer=track.querySelector(`.oval-racer[data-pilot="${pilot.id}"]`);
    const isNew=!racer;
    if(isNew){racer=document.createElement("div");racer.className="oval-racer";racer.dataset.pilot=pilot.id;racer.innerHTML=`<span class="racer-chat-slot"></span><img alt=""><span class="racer-info"><strong></strong><i class="racer-lap"></i><i class="racer-score"></i></span>`;track.append(racer);}
    const displayScore=state.deferredScores[pilot.id]??pilot.score,previousScore=Number(racer.dataset.score),lap=Math.min(state.room.laps,Math.floor(displayScore/100)+1),progress=displayScore>=total?0:displayScore%100,angle=(progress/100)*Math.PI*2,radiusX=42-(index%3)*2.6,radiusY=39-(index%3)*3;
    racer.style.left=`${50+radiusX*Math.cos(angle)}%`;racer.style.top=`${50+radiusY*Math.sin(angle)}%`;racer.style.setProperty("--racer-color",colors[index%colors.length]);
    racer.querySelector("img").src=pilot.photo;racer.querySelector("img").alt=`Foto de ${pilot.name}`;racer.querySelector("strong").textContent=pilot.name;racer.querySelector(".racer-lap").textContent=`VOLTA ${lap}/${state.room.laps}`;racer.querySelector(".racer-score").textContent=`${Math.min(displayScore,total)} / ${total}`;
    if(!isNew&&previousScore!==displayScore){const retreating=displayScore<previousScore;racer.classList.remove("is-advancing","is-retreating");void racer.offsetWidth;racer.classList.add(retreating?"is-retreating":"is-advancing");if(state.turboMovingId===pilot.id)racer.classList.add("is-turbo-moving");clearTimeout(racer._moveTimer);racer._moveTimer=setTimeout(()=>racer.classList.remove("is-advancing","is-retreating","is-turbo-moving"),1200);if(retreating)playNegativeMove();}
    racer.dataset.score=displayScore;
    const chat=state.chatBubbles[pilot.id],slot=racer.querySelector(".racer-chat-slot"),signature=chat?`${chat.emote}|${chat.message}`:"";
    if(slot.dataset.signature!==signature){slot.dataset.signature=signature;slot.innerHTML=chat?`<span class="racer-chat-bubble ${chat.isNew?"is-new":""}">${chatEmotes[chat.emote]?`<b>${chatEmotes[chat.emote]}</b>`:""}${escapeHTML(chat.message)}</span>`:"";}
    racer.classList.remove("is-targetable","is-selected-target");racer.classList.toggle("is-kickable",Boolean(isHost()&&!ownsPilot(pilot)&&pilot.id===state.pilots[state.turn]?.id&&canRollCurrentPilot()));
  });
  Object.values(state.chatBubbles).forEach(chat=>chat.isNew=false);renderTrackGiftPanel();renderAdminPilotPanel();renderRaceRoster();$("#currentPilot").textContent=state.pilots[state.turn]?.name||"—";announceTurn(state.pilots[state.turn]);renderChatControls();renderChatFeed();if(!state.turnPermissionTimer)state.turnPermissionTimer=setInterval(updateRollPermission,1000);
}
function queueScreenAnimation(callback){const generation=state.visualGeneration,start=Math.max(Date.now(),state.nextScreenAnimationAt),end=start+3000;state.nextScreenAnimationAt=end;state.sequenceLocked=true;updateRollPermission();setTimeout(()=>{if(generation===state.visualGeneration)callback();},Math.max(0,start-Date.now()));setTimeout(()=>{if(generation===state.visualGeneration&&state.nextScreenAnimationAt<=end){state.sequenceLocked=false;updateRollPermission();}},Math.max(0,end-Date.now()));}
function queueTrackMovement(pilotId,intermediateScore=null){if(!pilotId||state.deferredScores[pilotId]===undefined)return;queueScreenAnimation(()=>{if(Number.isFinite(intermediateScore))state.deferredScores[pilotId]=intermediateScore;else delete state.deferredScores[pilotId];renderRace();});}
function renderBirthdayCakes(track,pilot){track.querySelectorAll(".birthday-cake-marker").forEach(marker=>marker.remove());if(!isBirthdayActive()||!pilot)return;const claimed=new Set((state.room.birthdayCakeClaims||[]).map(item=>Number(item.marker)));for(const marker of [12,32,62,82]){if(claimed.has(marker))continue;const angle=marker/100*Math.PI*2,cake=document.createElement("div");cake.className="birthday-cake-marker";cake.dataset.marker=marker;cake.textContent="🎂";cake.style.left=`${50+42*Math.cos(angle)}%`;cake.style.top=`${50+39*Math.sin(angle)}%`;cake.innerHTML=`🎂<small>${marker}</small>`;track.append(cake);}}
function announceTurn(pilot,queued=false){if(!state.racing||!pilot||(!queued&&pilot.id===state.lastAnnouncedTurnId))return;if(!queued){state.lastAnnouncedTurnId=pilot.id;queueScreenAnimation(()=>announceTurn(pilot,true));return;}let notice=$("#turnAnnouncement");if(!notice){notice=document.createElement("div");notice.id="turnAnnouncement";notice.className="turn-announcement";notice.setAttribute("role","status");notice.setAttribute("aria-live","assertive");notice.innerHTML='<div><small>AGORA É A VEZ DE</small><img alt=""><strong></strong></div>';document.body.append(notice);}notice.querySelector("img").src=pilot.photo;notice.querySelector("img").alt=`Foto de ${pilot.name}`;notice.querySelector("strong").textContent=pilot.name;notice.hidden=false;notice.classList.remove("is-showing");requestAnimationFrame(()=>notice.classList.add("is-showing"));clearTimeout(state.turnAnnouncementTimer);state.turnAnnouncementTimer=setTimeout(()=>{notice.classList.remove("is-showing");setTimeout(()=>notice.hidden=true,250);},2500);}
function updateRollPermission(){if(!state.room||!state.racing)return;const turnAllowed=canRollCurrentPilot(),blocked=state.sequenceLocked||state.giftFlowActive||Boolean(state.room.pendingItem),allowed=turnAllowed&&!blocked,pilot=state.pilots[state.turn],hostWaiting=isHost()&&!ownsPilot(pilot)&&!turnAllowed,canKick=isHost()&&!ownsPilot(pilot)&&turnAllowed&&!blocked,remaining=Math.max(0,Math.ceil((new Date(state.room.turnStartedAt||0).getTime()+60000-Date.now())/1000));$("#rollButton").disabled=!allowed;$("#kickAbsentPilot").hidden=!canKick;$("#raceTrack")?.querySelectorAll(".oval-racer").forEach(r=>r.classList.toggle("is-kickable",canKick&&r.dataset.pilot===pilot?.id));$("#turnPermission").textContent=state.sequenceLocked?"Aguarde a sequência da jogada":state.giftFlowActive||state.room.pendingItem?"Resolva o presente para continuar":allowed?(isHost()&&!ownsPilot(pilot)?"Piloto ausente: role o dado ou remova-o pela lista lateral":"É a sua vez de jogar"):hostWaiting?`Aguardando ${pilot?.name||"o piloto"} · controle em ${remaining}s`:`Aguardando ${pilot?.name||"o piloto"}`;renderRaceRoster();}
function startDiceAnimation(){$("#rollButton").classList.add("is-rolling");$("#lastRoll").classList.add("is-rolling");playDiceRoll();}
function finishDiceAnimation(result){$("#rollButton").classList.remove("is-rolling");$("#lastRoll").classList.remove("is-rolling");if(result){playDiceResult(result);state.pendingLocalDiceValue=state.cloud?Number(result):null;showDiceResult(result);}}
function showDiceResult(result,queued=false){if(!queued){queueScreenAnimation(()=>showDiceResult(result,true));return;}const value=Math.max(1,Math.min(20,Number(result)||1)),intensity=(value-1)/19,track=$("#raceTrack");if(!track)return;let display=track.querySelector(".table-dice-result");if(!display){display=document.createElement("div");display.className="table-dice-result";display.innerHTML='<small>RESULTADO</small><strong></strong>';track.append(display);}display.style.setProperty("--roll-glow",intensity.toFixed(3));display.classList.toggle("is-high",value>=15);display.classList.toggle("is-critical",value===20);display.querySelector("strong").textContent=value;display.hidden=false;display.classList.remove("is-showing");requestAnimationFrame(()=>display.classList.add("is-showing"));clearTimeout(state.diceResultTimer);state.diceResultTimer=setTimeout(()=>{display.classList.remove("is-showing");setTimeout(()=>display.hidden=true,260);state.diceResultTimer=null;},2500);}
function nextTurn(){state.turn=(state.turn+1)%state.pilots.length;state.room.turnStartedAt=new Date().toISOString();setTimeout(()=>{$("#currentPilot").textContent=state.pilots[state.turn].name;announceTurn(state.pilots[state.turn]);updateRollPermission();},500);}
function crossedGiftMarker(pilot,from,to){pilot.claimedGifts=pilot.claimedGifts||[];const markers=[];for(let lap=0;lap<state.room.laps;lap++){for(const point of [25,50,75]){const absolute=lap*100+point,key=`${lap+1}-${point}`;if(from<absolute&&to>=absolute&&!pilot.claimedGifts.includes(key))markers.push({key,lap:lap+1,point,absolute});}}const marker=markers[0];if(marker)pilot.claimedGifts.push(marker.key);return marker;}
$("#startRace").onclick=startRace; $("#rollButton").onclick=()=>{if(!state.racing)return;if(state.sequenceLocked||state.giftFlowActive||state.room.pendingItem)return;if(!canRollCurrentPilot())return toast("Somente o dono deste corredor ou o anfitrião pode lançar.");const btn=$("#rollButton"),pilot=state.pilots[state.turn],total=state.room.laps*100;btn.disabled=true;startDiceAnimation();let ticks=0;const timer=setInterval(async()=>{$("#lastRoll").textContent=Math.floor(Math.random()*20)+1;if(++ticks<9)return;clearInterval(timer);if(state.cloud){try{const result=await rollRemoteD20(state.room.code);$("#lastRoll").textContent=result.roll;finishDiceAnimation(result.roll);await refreshCurrentRoom();updateRollPermission();}catch(error){finishDiceAnimation();toast(error.message);updateRollPermission();}return;}const roll=Math.floor(Math.random()*20)+1,previous=pilot.score;pilot.score+=roll;pilot.rolls++;const marker=crossedGiftMarker(pilot,previous,pilot.score);state.deferredScores[pilot.id]=previous;$("#lastRoll").textContent=roll;finishDiceAnimation(roll);queueTrackMovement(pilot.id);renderRace();if(pilot.score>=total){state.racing=false;queueScreenAnimation(()=>showWinner(pilot));}else if(marker){state.pendingGift=pilot;state.pendingMarker=marker;state.giftFlowActive=true;queueScreenAnimation(showMysteryGift);}else nextTurn();},65);};

const gifts=[{icon:"🐢",title:"CASCO D20",damage:15,text:"Escolha um rival para fazê-lo recuar 15 pontos."},{icon:"🍌",title:"BANANA CRÍTICA",damage:8,text:"Escolha um rival para fazê-lo recuar 8 pontos."},{icon:"⚡",title:"RAIO DO CAOS",damage:20,text:"Escolha um rival para fazê-lo recuar 20 pontos."},{icon:"🚀",title:"TURBO ÉPICO",boost:10,text:"Você avança mais 10 pontos imediatamente!"}];
function showMysteryGift(){const pilot=state.pendingGift,marker=state.pendingMarker;$("#giftIcon").textContent="🎁";$("#giftTitle").textContent=`PRESENTE DE ${pilot.name.toUpperCase()}`;$("#giftDescription").textContent=`Marco ${marker.point} da volta ${marker.lap}. Abra a caixa para descobrir o item.`;$("#openGift").hidden=false;$("#targetArea").hidden=true;$("#mysteryModal").hidden=false;}
function clearPendingTimers(){if(state.pendingExpiryTimer)clearTimeout(state.pendingExpiryTimer);if(state.pendingCountdown)clearInterval(state.pendingCountdown);state.pendingExpiryTimer=null;state.pendingCountdown=null;}
function hideRemoteItem(keepExpiryTimer=false){if(state.pendingCountdown)clearInterval(state.pendingCountdown);state.pendingCountdown=null;if(!keepExpiryTimer){if(state.pendingExpiryTimer)clearTimeout(state.pendingExpiryTimer);state.pendingExpiryTimer=null;}state.trackGift=null;state.queuedPendingGiftId=null;state.selectedTargetId=null;$("#mysteryModal").hidden=true;$("#targetArea").hidden=true;document.querySelector(".track-gift-panel")?.remove();document.querySelectorAll(".oval-racer").forEach(r=>r.classList.remove("is-targetable","is-selected-target"));}
function schedulePendingExpiry(item){if(!state.cloud||!state.room)return;if(state.pendingExpiryTimer)clearTimeout(state.pendingExpiryTimer);const expiresAt=new Date(item.expires_at||Date.now()+60000).getTime(),delay=Math.max(0,expiresAt-Date.now()+250),isItemOwner=ownsPilot(state.pilots.find(p=>p.id===item.player_id));state.pendingExpiryTimer=setTimeout(async()=>{try{const expired=await expireRemoteItem(state.room.code);if(expired){hideRemoteItem();if(isItemOwner)toast("O tempo do presente acabou. A vez foi perdida.");await refreshCurrentRoom();}}catch(error){toast(error.message);}},delay);}
function showRemoteItem(item,queued=false){const giftId=`${item.player_id}:${item.lap}:${item.marker}:${item.expires_at}`;if(!queued&&giftId!==state.queuedPendingGiftId){state.queuedPendingGiftId=giftId;queueScreenAnimation(()=>showRemoteItem(item,true));return;}if(!queued&&giftId===state.queuedPendingGiftId)return;const icons={shell:"🐢",banana:"🍌",lightning:"⚡"},titles={shell:"CASCO D20",banana:"BANANA CRÍTICA",lightning:"RAIO DO CAOS"},expiresAt=new Date(item.expires_at||Date.now()+60000).getTime();state.activeGift={damage:item.damage};state.pendingGift=state.pilots.find(p=>p.id===item.player_id);state.trackGift={...item,icon:icons[item.type]||"🎁",title:titles[item.type]||"ITEM MISTERIOSO",expiresAt};state.selectedTargetId=null;$("#mysteryModal").hidden=true;renderRace();if(state.pendingCountdown)clearInterval(state.pendingCountdown);state.pendingCountdown=setInterval(renderTrackGiftPanel,1000);updateRollPermission();}

function renderTrackGiftPanel(){const track=$("#raceTrack"),gift=state.trackGift;if(!track)return;let panel=track.querySelector(".track-gift-panel");if(!gift){panel?.remove();return;}if(!panel){panel=document.createElement("div");panel.className="track-gift-panel";panel.innerHTML='<span class="track-gift-icon"></span><small>PRESENTE ENCONTRADO</small><strong></strong><p></p><div class="gift-target-list"></div><button class="gift-target-confirm" type="button" disabled>SELECIONE UM CORREDOR</button>';track.append(panel);}const ordered=state.pilots.filter(p=>!p.isSpectator&&!p.spectatorOnly&&!p.finishPosition).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)),targets=ordered.filter(p=>p.id!==gift.player_id),selected=targets.find(p=>p.id===state.selectedTargetId),seconds=Math.max(0,Math.ceil((gift.expiresAt-Date.now())/1000));if(!selected)state.selectedTargetId=null;panel.querySelector(".track-gift-icon").textContent=gift.icon;panel.querySelector("strong").textContent=gift.title;panel.querySelector("p").textContent=selected?`${selected.name} será atingido em ${gift.damage} pontos · ${seconds}s`:`Escolha um rival pela ordem da corrida · ${seconds}s`;panel.querySelector(".gift-target-list").innerHTML=targets.map(p=>`<button type="button" class="gift-target-option ${p.id===state.selectedTargetId?"is-selected":""}" data-gift-target="${p.id}"><span>${ordered.indexOf(p)+1}º</span><img src="${p.photo}" alt=""><strong>${escapeHTML(p.name)}</strong><small>${p.score} PONTOS</small></button>`).join("");const button=panel.querySelector(".gift-target-confirm");button.disabled=!selected;button.textContent=selected?`CONFIRMAR ${selected.name.toUpperCase()}`:"SELECIONE UM CORREDOR";}

$("#raceTrack").onclick=e=>{const giftTarget=e.target.closest("[data-gift-target]");if(giftTarget&&state.trackGift){state.selectedTargetId=giftTarget.dataset.giftTarget;renderTrackGiftPanel();return;}const kickRacer=e.target.closest(".oval-racer.is-kickable");if(kickRacer&&!state.trackGift){state.adminSelectedPilotId=kickRacer.dataset.pilot;renderAdminPilotPanel();return;}const giftConfirm=e.target.closest(".gift-target-confirm");if(giftConfirm&&!giftConfirm.disabled&&state.selectedTargetId){giftConfirm.disabled=true;giftConfirm.textContent="APLICANDO...";$("#targetGrid").innerHTML=`<button data-target="${state.selectedTargetId}"></button>`;$("#targetGrid button").click();return;}const adminAction=e.target.closest(".admin-pilot-panel button");if(adminAction?.dataset.action==="cancel"){state.adminSelectedPilotId=null;renderAdminPilotPanel();}else if(adminAction?.dataset.action==="kick"){const pilot=state.pilots.find(p=>p.id===state.adminSelectedPilotId);if(pilot)kickAbsentPilot(pilot);}};

function renderAdminPilotPanel(){const track=$("#raceTrack"),pilot=state.pilots.find(p=>p.id===state.adminSelectedPilotId);let panel=track?.querySelector(".admin-pilot-panel");if(!pilot||state.trackGift){panel?.remove();return;}if(!panel){panel=document.createElement("div");panel.className="admin-pilot-panel";track.append(panel);}panel.innerHTML=`<img src="${pilot.photo}" alt=""><small>PILOTO AUSENTE</small><strong>${escapeHTML(pilot.name)}</strong><p>Deseja remover este corredor da sala?</p><div><button type="button" data-action="cancel">CANCELAR</button><button type="button" data-action="kick">EXPULSAR</button></div>`;}

function renderRaceRoster(){const list=$("#raceRosterList");if(!list)return;const raceFinished=state.room?.status==="finished",actions=$("#finishedRaceActions");actions.hidden=!raceFinished;$("#finishedRestartButton").hidden=!isHost();const current=state.pilots[state.turn],ordered=[...state.pilots].sort((a,b)=>Number(a.isSpectator)-Number(b.isSpectator)||(a.finishPosition&&b.finishPosition?a.finishPosition-b.finishPosition:a.finishPosition?-1:b.finishPosition?1:b.score-a.score)),signature=ordered.map(p=>`${p.id}:${p.score}:${p.finishPosition}:${p.isSpectator}:${p.spectatorOnly}:${p.id===current?.id}:${isHost()}`).join("|");if(list.dataset.signature===signature)return;list.dataset.signature=signature;list.innerHTML=ordered.map((pilot,index)=>{const currentPilot=pilot.id===current?.id,finished=Boolean(pilot.finishPosition);return `<article class="roster-pilot ${currentPilot?"is-current":""} ${finished?"is-finished":""} ${pilot.isSpectator?"is-spectator":""} ${pilot.finishPosition===1?"is-champion":""}"><span>${pilot.isSpectator?"•":finished?pilot.finishPosition:index+1}</span><img src="${pilot.photo}" alt=""><div><strong>${pilot.finishPosition===1?"👑 ":""}${escapeHTML(pilot.name)}</strong><small>${pilot.spectatorOnly?"ESPECTADOR":pilot.isSpectator?"AGUARDANDO PRÓXIMA CORRIDA":finished?`${pilot.finishPosition}º LUGAR`:currentPilot?"TURNO ATUAL":`${pilot.score} PONTOS`}</small></div>${isHost()?`<button type="button" data-remove-pilot="${pilot.id}" title="Remover perfil">×</button>`:""}</article>`;}).join("");}

$("#raceRosterList").onclick=async e=>{const button=e.target.closest("[data-remove-pilot]");if(!button||button.disabled)return;const pilot=state.pilots.find(p=>p.id===button.dataset.removePilot);if(!pilot)return;if(!confirm(`Remover ${pilot.name} da sala?`))return;try{if(state.cloud){await removeRemotePlayer(pilot.id);await refreshCurrentRoom();}else{state.pilots=state.pilots.filter(p=>p.id!==pilot.id);state.turn%=Math.max(1,state.pilots.length);syncRoom();renderRace();}toast(`${pilot.name} foi removido da sala.`);}catch(error){toast(error.message);}};
$("#finishedLobbyButton").onclick=()=>{state.postRaceLobby=true;state.racing=false;openRoom(state.room);};
$("#finishedRestartButton").onclick=()=>{if(isHost())startRace();};
function processPublicGiftEvent(room){const event=room.lastEvent;if(!event){state.lastEventId="none";return;}if(event.id===state.lastEventId)return;state.lastEventId=event.id;if(event.type==="birthday_cake")showBirthdayEvent(event);else if(event.type==="finish"&&event.turbo_before_finish){showPublicGiftEvent({id:`${event.id}-turbo`,type:"turbo",source_id:event.source_id,target_id:null,boost:event.boost||10});showFinishEvent(event);}else if(event.type==="finish")showFinishEvent(event);else if(event.type==="no_target")showNoTargetGift(event);else showPublicGiftEvent(event);}
function showBirthdayEvent(event,queued=false){if(!queued){queueScreenAnimation(()=>showBirthdayEvent(event,true));return;}const modal=$("#giftEventModal"),card=modal.querySelector(".gift-event-card"),participants=$("#giftEventParticipants"),icon=$("#giftEventIcon"),extra=event.effect==="extra_roll";participants.hidden=true;card.classList.remove("is-turbo","is-finish");card.classList.add("is-revealed","is-birthday");icon.classList.remove("is-spinning");icon.textContent="🎂";$("#giftEventTitle").textContent="FELIZ ANIVERSÁRIO!";$("#giftEventDescription").textContent=extra?"Feliz aniversário Irmãos Todd's, rode outro dado!":"Feliz aniversário Irmãos Todd's, seu bolo foi batizado! Você perdeu 3 posições.";modal.hidden=false;launchConfetti();playBirthday();if(!extra)playNegativeMove();const close=setTimeout(()=>{modal.hidden=true;card.classList.remove("is-revealed","is-birthday");delete state.deferredScores[event.source_id];renderRace();state.giftEventTimer=null;},2500);state.giftEventTimer={interval:null,reveal:null,close};}
function launchConfetti(){const layer=document.createElement("div");layer.className="birthday-confetti";for(let index=0;index<70;index++){const piece=document.createElement("i");piece.style.setProperty("--x",`${Math.random()*100}vw`);piece.style.setProperty("--delay",`${Math.random()*.5}s`);piece.style.setProperty("--duration",`${1.5+Math.random()*1.3}s`);piece.style.setProperty("--color",["#ffe600","#ff3b3b","#00f5ff","#ff4be0","#39e58c"][index%5]);layer.append(piece);}document.body.append(layer);setTimeout(()=>layer.remove(),3200);}
function showNoTargetGift(event,queued=false){if(!queued){queueScreenAnimation(()=>showNoTargetGift(event,true));return;}if(state.giftEventTimer){clearInterval(state.giftEventTimer.interval);clearTimeout(state.giftEventTimer.reveal);clearTimeout(state.giftEventTimer.close);}const icons={shell:"🐢",banana:"🍌",lightning:"⚡"},titles={shell:"CASCO D20",banana:"BANANA CRÍTICA",lightning:"RAIO DO CAOS"},pilot=state.pilots.find(p=>p.id===event.source_id),modal=$("#giftEventModal"),card=modal.querySelector(".gift-event-card"),participants=$("#giftEventParticipants"),icon=$("#giftEventIcon");participants.hidden=true;card.classList.add("is-revealed");icon.classList.remove("is-spinning");icon.textContent=icons[event.item_type]||"🎁";$("#giftEventTitle").textContent=titles[event.item_type]||"ITEM REVELADO";$("#giftEventDescription").textContent=`${pilot?.name||"O piloto"} encontrou o item, mas não há rivais na pista para atingir. O presente foi descartado.`;modal.hidden=false;playGiftReveal(event.item_type);const close=setTimeout(()=>{modal.hidden=true;card.classList.remove("is-revealed");state.giftEventTimer=null;},2500);state.giftEventTimer={interval:null,reveal:null,close};}
function showFinishEvent(event,queued=false){if(!queued){queueScreenAnimation(()=>showFinishEvent(event,true));return;}if(state.giftEventTimer){clearInterval(state.giftEventTimer.interval);clearTimeout(state.giftEventTimer.reveal);clearTimeout(state.giftEventTimer.close);}const pilot=state.pilots.find(p=>p.id===event.source_id),modal=$("#giftEventModal"),card=modal.querySelector(".gift-event-card"),icon=$("#giftEventIcon"),participants=$("#giftEventParticipants"),first=event.position===1;participants.hidden=false;participants.classList.add("finish-participant");$("#giftSourcePhoto").src=pilot?.photo||makeAvatar("D20");$("#giftSourceName").textContent=pilot?.name||"Piloto";$("#giftTargetPhoto").src=pilot?.photo||makeAvatar("D20");$("#giftTargetName").textContent=event.position?`${event.position}º LUGAR`:"FINALISTA";card.classList.remove("is-turbo");card.classList.add("is-revealed","is-finish");icon.classList.remove("is-spinning");icon.textContent=first?"👑":"🏁";$("#giftEventTitle").textContent=first?"NOVO LÍDER!":`${event.position}º LUGAR!`;$("#giftEventDescription").textContent=first?`${pilot?.name||"O piloto"} cruzou a linha de chegada primeiro!`:`${pilot?.name||"O piloto"} concluiu a corrida em ${event.position}º lugar.`;modal.hidden=false;if(first)playVictory();const close=setTimeout(()=>{modal.hidden=true;participants.hidden=true;participants.classList.remove("finish-participant");card.classList.remove("is-revealed","is-finish");delete state.deferredScores[event.source_id];renderRace();state.giftEventTimer=null;},2500);state.giftEventTimer={interval:null,reveal:null,close};}
function showPublicGiftEvent(event,queued=false){
  if(!queued){queueScreenAnimation(()=>showPublicGiftEvent(event,true));return;}
  if(state.giftEventTimer){clearInterval(state.giftEventTimer.interval);clearTimeout(state.giftEventTimer.reveal);clearTimeout(state.giftEventTimer.close);}
  const icons=["🐢","🍌","⚡","🚀"],finalIcons={shell:"🐢",banana:"🍌",lightning:"⚡",turbo:"🚀"},titles={shell:"CASCO D20!",banana:"BANANA CRÍTICA!",lightning:"RAIO DO CAOS!",turbo:"TURBO ÉPICO!"},source=state.pilots.find(p=>p.id===event.source_id),target=state.pilots.find(p=>p.id===event.target_id),isTurbo=event.type==="turbo",modal=$("#giftEventModal"),card=modal.querySelector(".gift-event-card"),icon=$("#giftEventIcon"),participants=$("#giftEventParticipants");
  let index=0;card.classList.remove("is-revealed","is-turbo");participants.hidden=true;icon.classList.add("is-spinning");$("#giftEventTitle").textContent="SORTEANDO ITEM...";$("#giftEventDescription").textContent="A caixa misteriosa foi ativada!";modal.hidden=false;
  const interval=setInterval(()=>{icon.textContent=icons[index++%icons.length];playGiftTick();},160);
  const reveal=setTimeout(()=>{clearInterval(interval);playGiftReveal(event.type);icon.classList.remove("is-spinning");icon.textContent=finalIcons[event.type]||"🎁";$("#giftEventTitle").textContent=titles[event.type]||"ITEM REVELADO!";$("#giftSourcePhoto").src=source?.photo||makeAvatar("D20");$("#giftSourceName").textContent=source?.name||"Piloto";if(isTurbo){participants.hidden=true;card.classList.add("is-turbo");$("#giftEventDescription").textContent=`${source?.name||"O piloto"} ativou o Nitro e avançou ${event.boost||15} pontos!`;}else{$("#giftTargetPhoto").src=target?.photo||makeAvatar("D20");$("#giftTargetName").textContent=target?.name||"Alvo";participants.hidden=false;$("#giftEventDescription").textContent=`${target?.name||"O alvo"} perdeu ${event.damage} pontos.`;}card.classList.add("is-revealed");},850);
  const close=setTimeout(()=>{modal.hidden=true;participants.hidden=true;card.classList.remove("is-revealed","is-turbo");const movingId=isTurbo?event.source_id:event.target_id;if(isTurbo){state.turboMovingId=movingId;playTurboMove();}delete state.deferredScores[movingId];renderRace();setTimeout(()=>{state.turboMovingId=null;},1300);state.giftEventTimer=null;},2500);
  state.giftEventTimer={interval,reveal,close};
}
$("#openGift").onclick=()=>{const gift=gifts[Math.floor(Math.random()*gifts.length)],pilot=state.pendingGift;state.activeGift=gift;$("#giftIcon").textContent=gift.icon;$("#giftTitle").textContent=gift.title;$("#giftDescription").textContent=gift.text;$("#openGift").hidden=true;if(gift.boost){pilot.score+=gift.boost;renderRace();setTimeout(()=>{const total=state.room.laps*100;$("#mysteryModal").hidden=true;state.giftFlowActive=false;if(pilot.score>=total){state.racing=false;showWinner(pilot);}else nextTurn();},1300);}else{$("#targetGrid").innerHTML=state.pilots.filter(p=>p.id!==pilot.id).map(p=>`<button class="target-button" data-target="${p.id}"><img src="${p.photo}" alt=""><span>${escapeHTML(p.name)}</span></button>`).join("");$("#targetArea").hidden=false;}};
$("#targetGrid").onclick=async e=>{const button=e.target.closest("[data-target]");if(!button)return;const target=state.pilots.find(p=>p.id===button.dataset.target),gift=state.activeGift;try{if(state.cloud){const result=await useRemoteItem(state.room.code,target.id);if(result.expired){hideRemoteItem();toast("O tempo do presente acabou.");await refreshCurrentRoom();return;}clearPendingTimers();$("#giftDescription").textContent=`${target.name} recuou ${gift.damage} pontos!`;$("#targetArea").hidden=true;await refreshCurrentRoom();setTimeout(()=>{$("#mysteryModal").hidden=true;updateRollPermission();},900);}else{target.score=Math.max(0,target.score-gift.damage);$("#giftDescription").textContent=`${target.name} recuou ${gift.damage} pontos!`;$("#targetArea").hidden=true;renderRace();setTimeout(()=>{$("#mysteryModal").hidden=true;state.giftFlowActive=false;nextTurn();},1100);}}catch(error){toast(error.message);}};

async function bootstrap(){renderDashboard();setPhoto(makeAvatar("D20"));const requested=new URLSearchParams(location.search).get("sala")?.toUpperCase();if(isSupabaseConfigured){try{const user=await ensureGuestSession();state.cloud=true;state.guestId=user.id;state.birthdayEvent=await getBirthdayEvent().catch(()=>null);scheduleBirthdayExpiry();state.rooms=(await listRemoteRooms()).map(normalizeRoom);$("#headerStatus").textContent="Online";renderDashboard();if(requested){const remote=await findRemoteRoom(requested);if(remote)openRoom(normalizeRoom(remote));else toast("Esta sala não existe.");}}catch(error){state.cloud=false;toast(`Modo local: ${error.message}`);}}else if(requested){const room=state.rooms.find(r=>r.code===requested);if(room)openRoom(room);else toast("Esta sala não existe neste navegador.");}}

$("#chatMessage").oninput=e=>$("#chatCharCount").textContent=`${e.target.value.length}/120`;
$("#chatForm").onsubmit=async e=>{e.preventDefault();const playerId=$("#chatPilot").value,message=$("#chatMessage").value.trim(),emote=$("#chatEmote").value;if(!message&&emote==="none")return toast("Escreva uma mensagem ou escolha um emote.");try{if(state.cloud)await sendChatMessage(state.room.code,playerId,message,emote);else showChatBubble({id:crypto.randomUUID(),player_id:playerId,message,emote,expires_at:new Date(Date.now()+20000).toISOString()});$("#chatMessage").value="";$("#chatEmote").value="none";$("#chatCharCount").textContent="0/120";}catch(error){toast(error.message);}};

async function kickAbsentPilot(pilot){if(!isHost()||ownsPilot(pilot)||!canRollCurrentPilot())return;try{state.adminSelectedPilotId=null;if(state.cloud){await removeRemotePlayer(pilot.id);await refreshCurrentRoom();}else{state.pilots=state.pilots.filter(p=>p.id!==pilot.id);state.turn%=Math.max(1,state.pilots.length);state.room.turnStartedAt=new Date().toISOString();syncRoom();renderRace();}toast(`${pilot.name} foi removido da sala.`);}catch(error){toast(error.message);}}
$("#kickAbsentPilot").onclick=()=>{const pilot=state.pilots[state.turn];if(pilot){state.adminSelectedPilotId=pilot.id;renderAdminPilotPanel();}};

bootstrap();
